# Generated by Django 5.2.4 on 2025-09-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_logo_gameimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='run_file',
            new_name='run_path',
        ),
        migrations.AddField(
            model_name='game',
            name='gamename',
            field=models.CharField(default=0, max_length=24),
            preserve_default=False,
        ),
    ]
