# Generated by Django 5.2.4 on 2025-09-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_rename_run_file_game_run_path_game_gamename'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='run_file',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
